version: "3"

volumes:
  cms-assets:
  
services:

    # API Gateway
  signomix-proxy:
    build:
      context: ../signomix-proxy
      args:
        DOMAIN: localhost
      dockerfile: ../signomix-proxy/Dockerfile
    networks:
      - signomix-network
    ports:
      - 80:80
      - 443:443
#    volumes:
#      - ~/signomix/volumes/volume-proxy:/etc/nginx/keys:rw

  signomix-mq:
    build:
      context: ../signomix-rabbitmq
      dockerfile: ../signomix-rabbitmq/Dockerfile
    hostname: signomix-mq
    container_name: signomix-mq
    networks:
      - signomix-network
    environment:
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: user
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  # signomix
  signomix-main:
    build:
      context: ../signomix
      dockerfile: ../signomix/Dockerfile
    networks:
      - signomix-network
    depends_on:
      - dbserver
      - signomix-mq
    environment:
      - SIGNOMIX_INITIAL_ADMIN_EMAIL=admin@myhost
      - SIGNOMIX_INITIAL_ADMIN_SECRET=test123
      - SIGNOMIX_ADMIN_NOTIFICATION_EMAIL=admin@myhost
      - SIGNOMIX_URL=https://myhost
      - SIGNOMIX_TITLE=Signomix
      - SIGNOMIX_DB_SERVER=dbserver
      - SIGNOMIX_APP_KEY=myappkey
      - QUEUE_HOST=signomix-mq
      - QUEUE_PORT=5672
      - QUEUE_USER=user
      - QUEUE_PASSWORD=user
      - QUEUE_NOTIFICATIONS=notifications
      - QUEUE_MAILING=mailing
      - QUEUE_ADMIN_EMAIL=admin_email
    volumes:
      - cms-assets:/usr/signomix/dbdata/assets
      - ~/signomix/volumes/volume-service/db:/usr/signomix/dbdata/db:rw
      - ~/signomix/volumes/volume-service/logs:/usr/signomix/dbdata/logs:rw
      - ~/signomix/volumes/volume-service/files:/usr/signomix/dbdata/files:rw
      - ~/signomix/volumes/volume-service/backup:/usr/signomix/dbdata/backup:rw
    
  # signomix publication service
  signomix-ta-ps:
    build:
      context: ../signomix-ta-ps
      dockerfile: ../signomix-ta-ps/src/main/docker/Dockerfile.jvm
    networks:
      - signomix-network
    environment:
      - SIGNOMIX_TITLE=Signomix
    volumes:
      - cms-assets:/usr/signomix/www/assets
      - ~/signomix/volumes/volume-ps:/usr/signomix/dbdata:rw
      - ~/signomix/volumes/volume-ps/logs:/usr/signomix/dbdata/logs:rw
  
  signomix-ta-app:
    build:
      context: ../signomix-ta-app
      dockerfile: ../signomix-ta-app/src/main/docker/Dockerfile.jvm
    restart: always
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
    environment:
      - SIGNOMIX_APP_KEY=myappkey
      - SIGNOMIX_AUTH_HOST_URL=http://signomix-main:8080
      - SIGNOMIX_STATUSPAGE_UR=https://status.myhost

  signomix-ta-ms:
    build:
      context: ../signomix-ta-ms
      dockerfile: ../signomix-ta-ms/src/main/docker/Dockerfile.jvm
    restart: always
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
    environment:
      - SIGNOMIX_TITLE=Signomix
      - SIGNOMIX_ENV_NAME=prod
      - SIGNOMIX_PUSHOVER_TOKEN=mypushovertoken
      - SIGNOMIX_SMTP_FROM=signomix@myhost
      - SIGNOMIX_SMTP_HOST=smtp.gmail.com
      - SIGNOMIX_SMTP_USER=admin@myhost
      - SIGNOMIX_SMTP_PASSWORD=mypassword
      - SIGNOMIX_SMTP_PORT=587
      - SIGNOMIX_SMTP_SSL=false
      - SIGNOMIX_SMTP_START_TLS=REQUIRED
      - SIGNOMIX_SMTP_AUTH_METHODS='DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN'
      - SIGNOMIX_SENTRY_PACKAGES=com.signomix
      - SIGNOMIX_SENTRY_LEVEL=ERROR
      - QUEUE_HOST=signomix-mq
      - QUEUE_PORT=5672
      - QUEUE_USER=user
      - QUEUE_PASSWORD=user
      - QUEUE_NOTIFICATIONS=notifications
      - QUEUE_MAILING=mailing
      - QUEUE_ADMIN_EMAIL=admin_email

  dbserver:
    build:
      context: ../signomix-database
      dockerfile: ../signomix-database/Dockerfile
    restart: always
    networks:
      - signomix-network
    expose:
      - 9092
    ports:
      - 9092:9092
    volumes:
      - ~/signomix/volumes/volume-db:/h2data:rw

networks:
  signomix-network:
    driver: bridge