version: "3"

#volumes:
#  cms-assets:

x-services-volume:
  &services-volume
  type: bind
  source: ${SGX_VOLUMES}/assets
  target: /usr/signomix/dbdata/assets

networks:
  signomix-network:
    driver: bridge

services:

  # API Gateway
  signomix-proxy:
    image: ${SGX_PROXY_NAME}:${SGX_PROXY_VERSION}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    ports:
      - 80:80
      - 443:443
    #TODO: for production use, mount volume with certificates
    #volumes:
    #  - ${SGX_VOLUME_PROXY}:/etc/nginx/keys:rw

  # MQ
  signomix-mq:
    image: rabbitmq:3-management-alpine
    container_name: signomix-mq
    hostname: signomix-mq
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    networks:
      - signomix-network
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 3

  # signomix
  signomix-main:
    image: ${SGX_MAIN_NAME}:${SGX_MAIN_VERSION}
    container_name: signomix-main
    hostname: signomix-main
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - dbserver
      - signomix-mq
      - signomix-ta-ms
    environment:
      - SIGNOMIX_INITIAL_ADMIN_EMAIL=${SGX_INITIAL_ADMIN_EMAIL}
      - SIGNOMIX_INITIAL_ADMIN_SECRET=${SGX_INITIAL_ADMIN_SECRET}
      - SIGNOMIX_ADMIN_NOTIFICATION_EMAIL=${SGX_ADMIN_NOTIFICATION_EMAIL}
      - SIGNOMIX_URL=${SGX_URL}
      - SIGNOMIX_TITLE=${SGX_TITLE}
      - SIGNOMIX_DB_SERVER=${SGX_DBSERVER}
      - SIGNOMIX_DATABASE_USER=${SGX_DATABASE_USER}
      - SIGNOMIX_DATABASE_PASSWORD=${SGX_DATABASE_PASSWORD}
      - SIGNOMIX_APP_KEY=${SGX_APP_KEY}
      - SIGNOMIX_COMMAND_ID_SIZE=8
      - SIGNOMIX_USER_ROLE_DEFAULT=
      - SIGNOMIX_USER_TYPE_DEFAULT=FREE
      - QUEUE_HOST=signomix-mq
      - QUEUE_PORT=5672
      - QUEUE_USER=user
      - QUEUE_PASSWORD=user
      - QUEUE_NOTIFICATIONS=notifications
      - QUEUE_MAILING=mailing
      - QUEUE_ADMIN_EMAIL=admin_email
    volumes:
      #- cms-assets:/usr/signomix/dbdata/assets
      - *services-volume
      - ${SGX_VOLUMES}/volume-service/db:/usr/signomix/dbdata/db:rw
      - ${SGX_VOLUMES}/volume-service/logs:/usr/signomix/dbdata/logs:rw
      - ${SGX_VOLUMES}/volume-service/files:/usr/signomix/dbdata/files:rw
      - ${SGX_VOLUMES}/volume-service/backup:/usr/signomix/dbdata/backup:rw
    
  signomix-ta-ms:
    image: ${SGX_MS_NAME}:${SGX_MS_VERSION}
    container_name: signomix-ta-ms
    hostname: signomix-ta-ms
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
    environment:
      - SIGNOMIX_TITLE=${SGX_TITLE}
      - SIGNOMIX_ENV_NAME=${SGX_ENV_NAME}
      - SIGNOMIX_PUSHOVER_TOKEN=${SGX_PUSHOVER_TOKEN}
      - SIGNOMIX_SMTP_FROM=${SGX_SMTP_FROM}
      - SIGNOMIX_SMTP_HOST=${SGX_SMTP_HOST}
      - SIGNOMIX_SMTP_LOGIN=${SGX_SMTP_LOGIN}
      - SIGNOMIX_SMTP_TRUST_ALL=${SGX_SMTP_TRUST_ALL}
      - SIGNOMIX_SMTP_USER=${SGX_SMTP_USER}
      - SIGNOMIX_SMTP_PASSWORD=${SGX_SMTP_PASSWORD}
      - SIGNOMIX_SMTP_PORT=${SGX_SMTP_PORT}
      - SIGNOMIX_SMTP_SSL=${SGX_SMTP_SSL}
      - SIGNOMIX_SMTP_START_TLS=${SGX_SMTP_START_TLS}
      - SIGNOMIX_SMTP_AUTH_METHODS=${SGX_SMTP_AUTH_METHODS}
      - SIGNOMIX_SENTRY_PACKAGES=com.signomix
      - SIGNOMIX_SENTRY_LEVEL=ERROR
      - SIGNOMIX_APP_KEY=${SGX_APP_KEY}
      #- SIGNOMIX_AUTH_DATABASE_URL=${SGX_AUTH_DATABASE_URL}
      #- SIGNOMIX_DATABASE_USER=${SGX_DATABASE_USER}
      #- SIGNOMIX_DATABASE_PASSWORD=${SGX_DATABASE_PASSWORD}
      - SIGNOMIX_DATABASE_URL=${POSTGRES_URL}
      - SIGNOMIX_DATABASE_USER=${POSTGRES_USER}
      - SIGNOMIX_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      #- SIGNOMIX_AUTH_HOST_URL=http://signomix-main:8080
      - SIGNOMIX_ADMIN_EMAIL=${SGX_ADMIN_NOTIFICATION_EMAIL}
      - QUEUE_HOST=signomix-mq
      - QUEUE_PORT=5672
      - QUEUE_USER=user
      - QUEUE_PASSWORD=user
      - QUEUE_NOTIFICATIONS=notifications
      - QUEUE_MAILING=mailing
      - QUEUE_ADMIN_EMAIL=admin_email
      - SIGNOMIX_DOC_WELCOME=/admin/welcomedoc

  # signomix publication service
  signomix-ta-ps:
    image: ${SGX_PS_NAME}:${SGX_PS_VERSION}
    container_name: signomix-ta-ps
    hostname: signomix-ta-ps
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    environment:
      - SIGNOMIX_TITLE=${SGX_TITLE}
    volumes:
      #- cms-assets:/usr/signomix/www/assets
      - <<: *services-volume
        target: /usr/signomix/www/assets
      - ${SGX_VOLUMES}/volume-ps:/usr/signomix/dbdata:rw
      - ${SGX_VOLUMES}/volume-ps/logs:/usr/signomix/dbdata/logs:rw

  signomix-ta-app:
    image: ${SGX_APP_NAME}:${SGX_APP_VERSION}
    container_name: signomix-ta-app
    hostname: signomix-ta-app
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
      - signomix-ta-ms
    environment:
      - SIGNOMIX_APP_KEY=${SGX_APP_KEY}
      - SIGNOMIX_AUTH_HOST_URL=http://signomix-main:8080
      - SIGNOMIX_STATUSPAGE_UR=https://status.myhost
      - SIGNOMIX_DATABASE_URL=${POSTGRES_URL}
      - SIGNOMIX_DATABASE_USER=${POSTGRES_USER}
      - SIGNOMIX_DATABASE_PASSWORD=${POSTGRES_PASSWORD}

  signomix-auth:
    image: ${SGX_AUTH_NAME}:${SGX_AUTH_VERSION}
    container_name: signomix-auth
    hostname: signomix-auth
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - dbserver
    environment:
      - SIGNOMIX_ORGANIZATION_DEFAULT=${SGX_ORGANIZATION_DEFAULT}
      - SIGNOMIX_DATABASE_TYPE=${SGX_DATABASE_TYPE}
      - SIGNOMIX_DATABASE_URL=${POSTGRES_URL}
      - SIGNOMIX_AUTH_DATABASE_URL=${POSTGRES_URL}
      - SIGNOMIX_USER_DATABASE_URL=${POSTGRES_URL}
      - SIGNOMIX_DATABASE_USER=${POSTGRES_USER}
      - SIGNOMIX_DATABASE_PASSWORD=${POSTGRES_PASSWORD}

  signomix-ta-provider:
    image: ${SGX_PROVIDER_NAME}:${SGX_PROVIDER_VERSION}
    container_name: signomix-ta-provider
    hostname: signomix-ta-provider
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
      - signomix-ta-ms
    environment:
      - SIGNOMIX_APP_KEY=${SGX_APP_KEY}
      - SIGNOMIX_CORE_HOST_URL=http://signomix-main:8080
      - SIGNOMIX_DATABASE_URL=${POSTGRES_URL}
      - SIGNOMIX_DATABASE_USER=${POSTGRES_USER}
      - SIGNOMIX_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      #- SIGNOMIX_AUTH_DATABASE_URL=${SGX_AUTH_DATABASE_URL}
      - SIGNOMIX_QUERY_LIMIT=${SGX_QUERY_LIMIT}
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - SIGNOMIX_LOG_LEVEL=INFO
      - QUARKUS_DATASOURCE_JDBC_MAX_SIZE=100

  signomix-ta-receiver:
    image: ${SGX_RECEIVER_NAME}:${SGX_RECEIVER_VERSION}
    container_name: signomix-ta-receiver
    hostname: signomix-ta-receiver
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
      - signomix-ta-ms
    environment:
      - SIGNOMIX_DATABASE_TYPE=${SGX_DATABASE_TYPE}
      - SIGNOMIX_APP_KEY=${SGX_APP_KEY}
      - SIGNOMIX_CORE_HOST_URL=http://signomix-main:8080
      - SIGNOMIX_DATABASE_URL=${SGX_DATABASE_URL}
      - SIGNOMIX_DATABASE_USER=${SGX_DATABASE_USER}
      - SIGNOMIX_DATABASE_PASSWORD=${SGX_DATABASE_PASSWORD}
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - SIGNOMIX_LOG_LEVEL=INFO
      - SIGNOMIX_EUI_HEADER_REQUIRED=${SGX_EUI_HEADER_REQUIRED}
      - SIGNOMIX_AUTHORIZATION_HEADER_REQUIRED=${SGX_AUTHORIZATION_HEADER_REQUIRED}
      - SIGNOMIX_STATUS_INTEGRATED=${SGX_STATUS_INTEGRATED}
      - QUARKUS_DATASOURCE_JDBC_MAX_SIZE=100
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}

  signomix-ta-account:
    image: ${SGX_ACCOUNT_NAME}:${SGX_ACCOUNT_VERSION}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
    environment:
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - MQ_EVENTS_QUEUE=events.account

  signomix-ta-core:
    image: ${SGX_CORE_NAME}:${SGX_CORE_VERSION}
    container_name: signomix-ta-core
    hostname: signomix-ta-core
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
    environment:
      - SIGNOMIX_APP_KEY=${SGX_APP_KEY}
      - SIGNOMIX_AUTH_HOST_URL=http://signomix-main:8080
      - SIGNOMIX_CORE_HOST_URL=http://signomix-main:8080
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - MQ_EVENTS_QUEUE=events.core
      - SIGNOMIX_LOG_LEVEL=DEBUG
      - SIGNOMIX_AUTH_DATABASE_URL=${SGX_AUTH_DATABASE_URL}
      - SIGNOMIX_USER_DATABASE_URL=${SGX_USER_DATABASE_URL}
      - SIGNOMIX_CMS_DATABASE_URL=${SGX_CMS_DATABASE_URL}
      - SIGNOMIX_IOT_DATABASE_URL=${SGX_IOT_DATABASE_URL}
      - SIGNOMIX_SHORTENER_DATABASE_URL=${SGX_SHORTENER_DATABASE_URL}
      - SIGNOMIX_DATABASE_USER=${SGX_DATABASE_USER}
      - SIGNOMIX_DATABASE_PASSWORD=${SGX_DATABASE_PASSWORD}
      - SIGNOMIX_DATABASE_TYPE=${SGX_DATABASE_TYPE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
      - SIGNOMIX_DATABASE_MIGRATION=${SGX_DATABASE_MIGRATION}

  signomix-ta-jobs:
    image: ${SGX_JOBS_NAME}:${SGX_JOBS_VERSION}
    container_name: signomix-ta-jobs
    hostname: signomix-ta-jobs
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
      - signomix-ta-ms
    environment:
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - SIGNOMIX_LOG_LEVEL=INFO
      - SIGNOMIX_DISK_FREE_MB=${SGX_DISK_FREE_MB}

  hcms:
    image: ${SGX_HCMS_NAME}:${SGX_HCMS_VERSION}
    expose:
      - "8080"
    networks:
      - signomix-network
    volumes:
      - ~/signomix/documents:/home/jboss/documents
  
  signomix-docs-website:
    image: ${SGX_DOCS_NAME}:${SGX_DOCS_VERSION}
    depends_on:
      - hcms
    expose:
      - "3000"
    networks:
      - signomix-network

  signomix-view:
    image: ${SGX_VIEW_NAME}:${SGX_VIEW_VERSION}
    expose:
      - "3000"
    networks:
      - signomix-network

  signomix-sentinel:
    image: ${SGX_SENTINEL_NAME}:${SGX_SENTINEL_VERSION}
    container_name: signomix-sentinel
    hostname: signomix-sentinel
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - tsserver
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  signomix-broker:
    image: eclipse-mosquitto:latest
    container_name: signomix-broker
    hostname: signomix-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ${SGX_VOLUMES}/mosquitto/config:/mosquitto/config
      - ${SGX_VOLUMES}/mosquitto/data:/mosquitto/data
      - ${SGX_VOLUMES}/mosquitto/log:/mosquitto/log
    networks:
      - signomix-network
    
  dbserver:
    image: ${SGX_DATABASE_NAME}:${SGX_DATABASE_VERSION}
    restart: always
    hostname: dbserver
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    expose:
      - 9092
    ports:
      - 9092:9092
    environment:
      - dbpassword=${SGX_DATABASE_PASSWORD}
    volumes:
      - ${SGX_VOLUMES}/volume-db:/h2data:rw
      - ${SGX_VOLUMES}/volume-dbbackup:/h2/backup:rw


  #database
  # https://github.com/timescale/timescaledb-dockertimeseries
  # https://hub.docker.com/_/postgres
  tsserver:
    image: timescale/timescaledb:latest-pg15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT_PUBLISHED}:5432
    expose:
      - 5432
    networks:
      - signomix-network
    volumes:
      - ${SGX_VOLUMES}/${POSTGRES_VOLUME}:/var/lib/postgresql/data:rw

  #jaeger-all-in-one:
  #  image: jaegertracing/all-in-one:latest
  #  ports:
  #    - 16686:16686 # Jaeger UI
  #    #- "14268:14268" # Receive legacy OpenTracing traces, optional
  #    - 4317:4317   # OTLP gRPC receiver
  #    #- "4318:4318"   # OTLP HTTP receiver, not yet used by Quarkus, optional
  #    #- "14250:14250" # Receive from external otel-collector, optional
  #  environment:
  #    - COLLECTOR_OTLP_ENABLED=true
  #  networks:
  #    - signomix-network

      
