version: "3"

#volumes:
#  cms-assets:

x-services-volume:
  &services-volume
  type: bind
  source: /home/signomix/signomix/volumes/assets
  target: /usr/signomix/dbdata/assets
  
services:

  # API Gateway
  signomix-proxy:
    image: ${SGX_PROXY_NAME}:${SGX_PROXY_VERSION}
    restart: always
    networks:
      - signomix-network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${SGX_VOLUME_PROXY}:/etc/nginx/keys:rw

  # MQ
  signomix-mq:
    image: rabbitmq:3-management-alpine
    container_name: signomix-mq
    hostname: signomix-mq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    networks:
      - signomix-network
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 3

  # signomix
  signomix-main:
    image: ${SGX_MAIN_NAME}:${SGX_MAIN_VERSION}
    container_name: signomix-main
    hostname: signomix-main
    networks:
      - signomix-network
    depends_on:
      - dbserver
      - signomix-mq
      - signomix-ta-ms
    environment:
      - SIGNOMIX_INITIAL_ADMIN_EMAIL=${SGX_INITIAL_ADMIN_EMAIL}
      - SIGNOMIX_INITIAL_ADMIN_SECRET=${SGX_INITIAL_ADMIN_SECRET}
      - SIGNOMIX_ADMIN_NOTIFICATION_EMAIL=${SGX_ADMIN_NOTIFICATION_EMAIL}
      - SIGNOMIX_URL=${SGX_URL}
      - SIGNOMIX_TITLE=${SGX_TITLE}
      - SIGNOMIX_DB_SERVER=${SGX_DBSERVER}
      - SIGNOMIX_DATABASE_USER=${SGX_DATABASE_USER}
      - SIGNOMIX_DATABASE_PASSWORD=${SGX_DATABASE_PASSWORD}
      - SIGNOMIX_APP_KEY=${SGX_APP_KEY}
      - SIGNOMIX_COMMAND_ID_SIZE=8
      - SIGNOMIX_USER_ROLE_DEFAULT=
      - SIGNOMIX_USER_TYPE_DEFAULT=FREE
      - QUEUE_HOST=signomix-mq
      - QUEUE_PORT=5672
      - QUEUE_USER=user
      - QUEUE_PASSWORD=user
      - QUEUE_NOTIFICATIONS=notifications
      - QUEUE_MAILING=mailing
      - QUEUE_ADMIN_EMAIL=admin_email
    volumes:
      #- cms-assets:/usr/signomix/dbdata/assets
      - *services-volume
      - ~/signomix/volumes/volume-service/db:/usr/signomix/dbdata/db:rw
      - ~/signomix/volumes/volume-service/logs:/usr/signomix/dbdata/logs:rw
      - ~/signomix/volumes/volume-service/files:/usr/signomix/dbdata/files:rw
      - ~/signomix/volumes/volume-service/backup:/usr/signomix/dbdata/backup:rw
    
  signomix-ta-ms:
    image: ${SGX_MS_NAME}:${SGX_MS_VERSION}
    container_name: signomix-ta-ms
    hostname: signomix-ta-ms
    restart: always
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
    environment:
      - SIGNOMIX_TITLE=${SGX_TITLE}
      - SIGNOMIX_ENV_NAME=${SGX_ENV_NAME}
      - SIGNOMIX_PUSHOVER_TOKEN=${SGX_PUSHOVER_TOKEN}
      - SIGNOMIX_SMTP_FROM=${SGX_SMTP_FROM}
      - SIGNOMIX_SMTP_HOST=${SGX_SMTP_HOST}
      - SIGNOMIX_SMTP_LOGIN=${SGX_SMTP_LOGIN}
      - SIGNOMIX_SMTP_USER=${SGX_SMTP_USER}
      - SIGNOMIX_SMTP_PASSWORD=${SGX_SMTP_PASSWORD}
      - SIGNOMIX_SMTP_PORT=${SGX_SMTP_PORT}
      - SIGNOMIX_SMTP_SSL=${SGX_SMTP_SSL}
      - SIGNOMIX_SMTP_START_TLS=${SGX_SMTP_START_TLS}
      - SIGNOMIX_SMTP_AUTH_METHODS=${SGX_SMTP_AUTH_METHODS}
      - SIGNOMIX_SMTP_TRUST_ALL=${SGX_SMTP_TRUST_ALL}
      - SIGNOMIX_SENTRY_PACKAGES=com.signomix
      - SIGNOMIX_SENTRY_LEVEL=ERROR
      - SIGNOMIX_APP_KEY=${SGX_APP_KEY}
      - SIGNOMIX_AUTH_DATABASE_URL=${SGX_AUTH_DATABASE_URL}
      - SIGNOMIX_AUTH_DATABASE_USER=${SGX_AUTH_DATABASE_USER}
      - SIGNOMIX_AUTH_DATABASE_PASSWORD=${SGX_AUTH_DATABASE_PASSWORD}
      - SIGNOMIX_AUTH_HOST_URL=http://signomix-main:8080
      - QUEUE_HOST=signomix-mq
      - QUEUE_PORT=5672
      - QUEUE_USER=user
      - QUEUE_PASSWORD=user
      - QUEUE_NOTIFICATIONS=notifications
      - QUEUE_MAILING=mailing
      - QUEUE_ADMIN_EMAIL=admin_email

  # signomix publication service
  signomix-ta-ps:
    image: ${SGX_PS_NAME}:${SGX_PS_VERSION}
    container_name: signomix-ta-ps
    hostname: signomix-ta-ps
    networks:
      - signomix-network
    environment:
      - SIGNOMIX_TITLE=${SGX_TITLE}
    volumes:
      #- cms-assets:/usr/signomix/www/assets
      - <<: *services-volume
        target: /usr/signomix/www/assets
      - ~/signomix/volumes/volume-ps:/usr/signomix/dbdata:rw
      - ~/signomix/volumes/volume-ps/logs:/usr/signomix/dbdata/logs:rw
  
  signomix-ta-app:
    image: ${SGX_APP_NAME}:${SGX_APP_VERSION}
    container_name: signomix-ta-app
    hostname: signomix-ta-app
    restart: always
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
    environment:
      - SIGNOMIX_APP_KEY=${SGX_APP_KEY}
      - SIGNOMIX_AUTH_HOST_URL=http://signomix-main:8080
      - SIGNOMIX_STATUSPAGE_UR=https://status.myhost
      
  signomix-ta-provider:
    image: ${SGX_PROVIDER_NAME}:${SGX_PROVIDER_VERSION}
    container_name: signomix-ta-provider
    hostname: signomix-ta-provider
    restart: always
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
      - signomix-ta-ms
    environment:
      - SIGNOMIX_APP_KEY=${SGX_APP_KEY}
      - SIGNOMIX_CORE_HOST_URL=http://signomix-main:8080
      - SIGNOMIX_DATABASE_URL=${SGX_DATABASE_URL}
      - SIGNOMIX_DATABASE_USER=${SGX_DATABASE_USER}
      - SIGNOMIX_DATABASE_PASSWORD=${SGX_DATABASE_PASSWORD}
      - SIGNOMIX_AUTH_DATABASE_URL=${SGX_AUTH_DATABASE_URL}
      - SIGNOMIX_AUTH_DATABASE_USER=${SGX_AUTH_DATABASE_USER}
      - SIGNOMIX_AUTH_DATABASE_PASSWORD=${SGX_AUTH_DATABASE_PASSWORD}
      - SIGNOMIX_QUERY_LIMIT=${SGX_QUERY_LIMIT}
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - SIGNOMIX_LOG_LEVEL=INFO

  signomix-ta-receiver:
    image: ${SGX_RECEIVER_NAME}:${SGX_RECEIVER_VERSION}
    container_name: signomix-ta-receiver
    hostname: signomix-ta-receiver
    restart: always
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
      - signomix-ta-ms
    environment:
      - SIGNOMIX_APP_KEY=${SGX_APP_KEY}
      - SIGNOMIX_CORE_HOST_URL=http://signomix-main:8080
      - SIGNOMIX_DATABASE_URL=${SGX_DATABASE_URL}
      - SIGNOMIX_DATABASE_USER=${SGX_DATABASE_USER}
      - SIGNOMIX_DATABASE_PASSWORD=${SGX_DATABASE_PASSWORD}
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - SIGNOMIX_LOG_LEVEL=INFO
      - SIGNOMIX_EUI_HEADER_REQUIRED=${SGX_EUI_HEADER_REQUIRED}
      - SIGNOMIX_AUTHORIZATION_HEADER_REQUIRED=${SGX_AUTHORIZATION_HEADER_REQUIRED}

  signomix-ta-account:
    image: ${SGX_ACCOUNT_NAME}:${SGX_ACCOUNT_VERSION}
    restart: always
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
    environment:
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - MQ_EVENTS_QUEUE=events.account

  signomix-ta-core:
    image: ${SGX_CORE_NAME}:${SGX_CORE_VERSION}
    container_name: signomix-ta-core
    hostname: signomix-ta-core
    restart: always
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
    environment:
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - MQ_EVENTS_QUEUE=events.core

  signomix-ta-jobs:
    image: ${SGX_JOBS_NAME}:${SGX_JOBS_VERSION}
    container_name: signomix-ta-jobs
    hostname: signomix-ta-jobs
    restart: always
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
    environment:
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - SIGNOMIX_LOG_LEVEL=INFO

  dbserver:
    image: ${SGX_DATABASE_NAME}:${SGX_DATABASE_VERSION}
    container_name: dbserver
    hostname: dbserver
    restart: always
    networks:
      - signomix-network
    expose:
      - 9092
    ports:
      - 9092:9092
    environment:
      - dbpassword=${SGX_DATABASE_PASSWORD}
    volumes:
      - ~/signomix/volumes/volume-db:/h2data:rw

networks:
  signomix-network:
    driver: bridge