#version: "3"

networks:
  signomix-network:
    driver: bridge

services:

  # API Gateway
  signomix-gateway:
    image: ${SGX_DOCKER_GROUP}${SGX_GATEWAY_NAME}:${SGX_GATEWAY_VERSION}
    restart: always
    container_name: signomix-gateway
    hostname: signomix-gateway
    depends_on:
      - tsserver
      - quest
      - signomix-auth
      - signomix-ta-provider
      - signomix-ta-receiver
      - signomix-ta-account
      - signomix-ta-jobs
      - signomix-ta-core
      - signomix-ta-app
      - signomix-ta-ms
      - signomix-sentinel
      - signomix-reports
      - signomix-broker
      - signomix-docs-website
      - signomix-view
      - signomix-webapp
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    ports:
      - 80:80
    #  - 443:443
    #volumes:
    #  - ${SGX_VOLUME_PROXY}/ssl:/etc/ssl/certs:rw
    #  - ${SGX_VOLUME_PROXY}/etc:/usr/local/etc/haproxy:rw

  # MQ
  signomix-mq:
    image: rabbitmq:3-management-alpine
    container_name: signomix-mq
    hostname: signomix-mq
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    networks:
      - signomix-network
    expose:
      # AMQP protocol port
      - "5672"
      # HTTP management UI
      - "15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 3

  signomix-ta-ms:
    image: ${SGX_DOCKER_GROUP}${SGX_MS_NAME}:${SGX_MS_VERSION}
    container_name: signomix-ta-ms
    hostname: signomix-ta-ms
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
    environment:
      - SIGNOMIX_TITLE=${SGX_TITLE}
      - SIGNOMIX_URL=${SGX_URL}
      - SIGNOMIX_ENV_NAME=${SGX_ENV_NAME}
      - SIGNOMIX_PUSHOVER_TOKEN=${SGX_PUSHOVER_TOKEN}
      - SIGNOMIX_SMTP_FROM=${SGX_SMTP_FROM}
      - SIGNOMIX_SMTP_HOST=${SGX_SMTP_HOST}
      - SIGNOMIX_SMTP_LOGIN=${SGX_SMTP_LOGIN}
      - SIGNOMIX_SMTP_TRUST_ALL=${SGX_SMTP_TRUST_ALL}
      - SIGNOMIX_SMTP_USER=${SGX_SMTP_USER}
      - SIGNOMIX_SMTP_PASSWORD=${SGX_SMTP_PASSWORD}
      - SIGNOMIX_SMTP_PORT=${SGX_SMTP_PORT}
      - SIGNOMIX_SMTP_SSL=${SGX_SMTP_SSL}
      - SIGNOMIX_SMTP_START_TLS=${SGX_SMTP_START_TLS}
      - SIGNOMIX_SMTP_AUTH_METHODS=${SGX_SMTP_AUTH_METHODS}
      - SIGNOMIX_SENTRY_PACKAGES=com.signomix
      - SIGNOMIX_SENTRY_LEVEL=ERROR
      - SIGNOMIX_DATABASE_URL=${POSTGRES_URL}
      - SIGNOMIX_DATABASE_USER=${POSTGRES_USER}
      - SIGNOMIX_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - SIGNOMIX_ADMIN_EMAIL=${SGX_ADMIN_NOTIFICATION_EMAIL}
      - QUEUE_HOST=signomix-mq
      - QUEUE_PORT=5672
      - QUEUE_USER=user
      - QUEUE_PASSWORD=user
      - QUEUE_NOTIFICATIONS=notifications
      - QUEUE_MAILING=mailing
      - QUEUE_ADMIN_EMAIL=admin_email
      - SIGNOMIX_DOC_WELCOME=/admin/welcomedoc
      - SIGNOMIX_LOG_LEVEL=${SGX_LOG_LEVEL}
      - SIGNOMIX_SMSPLANET_KEY=${SGX_SMSPLANET_KEY}
      - SIGNOMIX_SMSPLANET_PASSWORD=${SGX_SMSPLANET_PASSWORD}

  signomix-ta-app:
    image: ${SGX_DOCKER_GROUP}${SGX_APP_NAME}:${SGX_APP_VERSION}
    container_name: signomix-ta-app
    hostname: signomix-ta-app
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
      - signomix-ta-ms
    environment:
      #- SIGNOMIX_APP_KEY=${SGX_APP_KEY}
      - SIGNOMIX_STATUSPAGE_UR=https://status.myhost
      - SIGNOMIX_DATABASE_URL=${POSTGRES_URL}
      - SIGNOMIX_DATABASE_USER=${POSTGRES_USER}
      - SIGNOMIX_DATABASE_PASSWORD=${POSTGRES_PASSWORD}

  signomix-auth:
    image: ${SGX_DOCKER_GROUP}${SGX_AUTH_NAME}:${SGX_AUTH_VERSION}
    container_name: signomix-auth
    hostname: signomix-auth
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    environment:
      - SIGNOMIX_ORGANIZATION_DEFAULT=${SGX_ORGANIZATION_DEFAULT}
      - SIGNOMIX_DATABASE_TYPE=${SGX_DATABASE_TYPE}
      - SIGNOMIX_DATABASE_URL=${POSTGRES_URL}
      - SIGNOMIX_AUTH_DATABASE_URL=${POSTGRES_URL}
      - SIGNOMIX_USER_DATABASE_URL=${POSTGRES_URL}
      - SIGNOMIX_DATABASE_USER=${POSTGRES_USER}
      - SIGNOMIX_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - QUARKUS_OTEL_TRACES_EXPORTER=${QUARKUS_OTEL_TRACES_EXPORTER}
      - SIGNOMIX_QUESTDB_CONFIG=${SGX_QUESTDB_CONFIG}

  signomix-ta-provider:
    image: ${SGX_DOCKER_GROUP}${SGX_PROVIDER_NAME}:${SGX_PROVIDER_VERSION}
    container_name: signomix-ta-provider
    hostname: signomix-ta-provider
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
      - signomix-ta-ms
    environment:
      - SIGNOMIX_DATABASE_URL=${POSTGRES_URL}
      - SIGNOMIX_DATABASE_USER=${POSTGRES_USER}
      - SIGNOMIX_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - SIGNOMIX_QUERY_LIMIT=${SGX_QUERY_LIMIT}
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - SIGNOMIX_LOG_LEVEL=INFO
      - QUARKUS_OTEL_TRACES_EXPORTER=${QUARKUS_OTEL_TRACES_EXPORTER}
      - QUARKUS_DATASOURCE_JDBC_MAX_SIZE=100

  signomix-ta-receiver:
    image: ${SGX_DOCKER_GROUP}${SGX_RECEIVER_NAME}:${SGX_RECEIVER_VERSION}
    container_name: signomix-ta-receiver
    hostname: signomix-ta-receiver
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
      - signomix-ta-ms
    environment:
      - SIGNOMIX_DATABASE_TYPE=${SGX_DATABASE_TYPE}
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - SIGNOMIX_LOG_LEVEL=INFO
      - SIGNOMIX_EUI_HEADER_REQUIRED=${SGX_EUI_HEADER_REQUIRED}
      - SIGNOMIX_AUTHORIZATION_HEADER_REQUIRED=${SGX_AUTHORIZATION_HEADER_REQUIRED}
      - SIGNOMIX_STATUS_INTEGRATED=${SGX_STATUS_INTEGRATED}
      - QUARKUS_DATASOURCE_JDBC_MAX_SIZE=100
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}

  signomix-ta-account:
    image: ${SGX_DOCKER_GROUP}${SGX_ACCOUNT_NAME}:${SGX_ACCOUNT_VERSION}
    container_name: signomix-ta-account
    hostname: signomix-ta-account
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    environment:
      - SIGNOMIX_DATABASE_TYPE=${SGX_DATABASE_TYPE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}

  signomix-ta-core:
    image: ${SGX_DOCKER_GROUP}${SGX_CORE_NAME}:${SGX_CORE_VERSION}
    container_name: signomix-ta-core
    hostname: signomix-ta-core
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
    environment:
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - MQ_EVENTS_QUEUE=events.core
      - SIGNOMIX_LOG_LEVEL=DEBUG
      - SIGNOMIX_AUTH_DATABASE_URL=${SGX_AUTH_DATABASE_URL}
      - SIGNOMIX_USER_DATABASE_URL=${SGX_USER_DATABASE_URL}
      - SIGNOMIX_CMS_DATABASE_URL=${SGX_CMS_DATABASE_URL}
      - SIGNOMIX_IOT_DATABASE_URL=${SGX_IOT_DATABASE_URL}
      - SIGNOMIX_SHORTENER_DATABASE_URL=${SGX_SHORTENER_DATABASE_URL}
      - SIGNOMIX_DATABASE_TYPE=${SGX_DATABASE_TYPE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
      - SIGNOMIX_DATABASE_MIGRATION=${SGX_DATABASE_MIGRATION}

  signomix-ta-jobs:
    image: ${SGX_DOCKER_GROUP}${SGX_JOBS_NAME}:${SGX_JOBS_VERSION}
    container_name: signomix-ta-jobs
    hostname: signomix-ta-jobs
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - signomix-mq
      - signomix-ta-ms
    environment:
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - SIGNOMIX_LOG_LEVEL=INFO
      - SIGNOMIX_DISK_FREE_MB=${SGX_DISK_FREE_MB}

  hcms:
    image: ${SGX_DOCKER_GROUP}${SGX_HCMS_NAME}:${SGX_HCMS_VERSION}
    container_name: hcms
    hostname: hcms
    expose:
      - "8080"
    networks:
      - signomix-network
    environment:
      - FILE_TO_WATCH=signomix/version.txt;templates/version.txt
      - FOLDERS_EXCLUDED=signomix/.git;signomix/attic;templates/.git;templates/attic
    volumes:
      - ${SGX_VOLUMES}/documents/templates:/home/jboss/documents/templates
      - ${SGX_VOLUMES}/documents/signomix-documentation:/home/jboss/documents/signomix

  website-hcms:
    image: ${SGX_DOCKER_GROUP}${SGX_HCMS_NAME}:${SGX_WEBSITE_HCMS_VERSION}
    container_name: website-hcms
    hostname: website-hcms
    expose:
      - "8080"
    networks:
      - signomix-network
    volumes:
      - ${SGX_VOLUMES}/signomix-website-content:/home/jboss/documents
  
  signomix-docs-website:
    image: ${SGX_DOCKER_GROUP}${SGX_DOCS_NAME}:${SGX_DOCS_VERSION}
    container_name: signomix-docs-website
    hostname: signomix-docs-website
    depends_on:
      - hcms
    expose:
      - "3000"
    networks:
      - signomix-network

#  signomix-website:
#    image: ${SGX_DOCKER_GROUP}${SGX_WEBSITE_NAME}:${SGX_WEBSITE_VERSION}
#    container_name: signomix-website
#    hostname: signomix-website
#    depends_on:
#      - website-hcms
#    expose:
#      - "3000"
#    networks:
#      - signomix-network

  signomix-view:
    image: ${SGX_DOCKER_GROUP}${SGX_VIEW_NAME}:${SGX_VIEW_VERSION}
    container_name: signomix-view
    hostname: signomix-view
    expose:
      - "3000"
    networks:
      - signomix-network

  signomix-webapp:
    image: ${SGX_DOCKER_GROUP}${SGX_WEBAPP_NAME}:${SGX_WEBAPP_VERSION}
    container_name: signomix-webapp
    hostname: signomix-webapp
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - signomix-network

  signomix-sentinel:
    image: ${SGX_DOCKER_GROUP}${SGX_SENTINEL_NAME}:${SGX_SENTINEL_VERSION}
    container_name: signomix-sentinel
    hostname: signomix-sentinel
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - tsserver
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - QUARKUS_OTEL_TRACES_EXPORTER=${QUARKUS_OTEL_TRACES_EXPORTER}

  signomix-reports:
    image: ${SGX_DOCKER_GROUP}${SGX_REPORTS_NAME}:${SGX_REPORTS_VERSION}
    container_name: signomix-reports
    hostname: signomix-reports
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - tsserver
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - QUARKUS_OTEL_TRACES_EXPORTER=${QUARKUS_OTEL_TRACES_EXPORTER}

  signomix-broker:
    image: eclipse-mosquitto:latest
    container_name: signomix-broker
    hostname: signomix-broker
    restart: always
    expose:
      - "1883"
      - "9001"
    volumes:
      - ${SGX_VOLUMES}/mosquitto/config:/mosquitto/config
      - ${SGX_VOLUMES}/mosquitto/data:/mosquitto/data
      - ${SGX_VOLUMES}/mosquitto/log:/mosquitto/log
    networks:
      - signomix-network
    

  # TimescaleDB database
  # https://github.com/timescale/timescaledb-dockertimeseries
  # https://hub.docker.com/_/postgres
  tsserver:
    image: timescale/timescaledb:latest-pg15
    restart: always
    container_name: tsserver
    hostname: tsserver
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT_PUBLISHED}:5432
    expose:
      - 5432
    networks:
      - signomix-network
    volumes:
      - ${SGX_VOLUMES}/volume-postgres:/var/lib/postgresql/data:rw

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-all-in-one
    hostname: jaeger-all-in-one
    ports:
      - 16686:16686 # Jaeger UI
      #- "14268:14268" # Receive legacy OpenTracing traces, optional
      - 4317:4317   # OTLP gRPC receiver
      #- "4318:4318"   # OTLP HTTP receiver, not yet used by Quarkus, optional
      #- "14250:14250" # Receive from external otel-collector, optional
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=badger
    networks:
      - signomix-network

  quest:
    image: questdb/questdb:7.4.0
    container_name: quest
    hostname: quest
    ports:
      - 9000:9000
#      - 9009:9009
#      - 8812:8812
#      - 9003:9003
    volumes:
      - ${SGX_VOLUMES}/volume-questdb:/var/lib/questdb
    networks:
      - signomix-network
