services:

  # API Gateway
  signomix-gateway:
    image: ${SGX_DOCKER_GROUP}${SGX_GATEWAY_NAME}:${SGX_GATEWAY_VERSION}
    restart: always
    container_name: signomix-gateway
    hostname: signomix-gateway
    depends_on:
      - tsserver
      - quest
      - signomix-auth
      - signomix-ta-provider
      - signomix-ta-receiver
      - signomix-ta-account
      - signomix-ta-jobs
      - signomix-ta-core
      - signomix-ta-ms
      - signomix-sentinel
      - signomix-reports
      - signomix-broker
      - signomix-docs-website
      - signomix-view
      - signomix-webapp
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    ports:
      - 80:80
    #  - 443:443
    #volumes:
    #  - ${SGX_VOLUME_PROXY}/ssl:/etc/ssl/certs:rw
    #  - ${SGX_VOLUME_PROXY}/etc:/usr/local/etc/haproxy:rw

  signomix-ta-ms:
    image: ${SGX_DOCKER_GROUP}${SGX_MS_NAME}:${SGX_MS_VERSION}
    container_name: signomix-ta-ms
    hostname: signomix-ta-ms
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    environment:
      - SIGNOMIX_TITLE=${SGX_TITLE}
      - SIGNOMIX_URL=${SGX_URL}
      - SIGNOMIX_ENV_NAME=${SGX_ENV_NAME}
      - SIGNOMIX_PUSHOVER_TOKEN=${SGX_PUSHOVER_TOKEN}
      - SIGNOMIX_SMTP_HOST=${SGX_SMTP_HOST}
      - SIGNOMIX_SMTP_TRUST_ALL=${SGX_SMTP_TRUST_ALL}
      - SIGNOMIX_SMTP_PORT=${SGX_SMTP_PORT}
      - SIGNOMIX_SMTP_SSL=${SGX_SMTP_SSL}
      - SIGNOMIX_SMTP_START_TLS=${SGX_SMTP_START_TLS}
      - SIGNOMIX_SMTP_AUTH_METHODS=${SGX_SMTP_AUTH_METHODS}
      - SIGNOMIX_SENTRY_PACKAGES=com.signomix
      - SIGNOMIX_SENTRY_LEVEL=ERROR
      - SIGNOMIX_DATABASE_URL=${POSTGRES_URL}
      - SIGNOMIX_DATABASE_USER=${POSTGRES_USER}
      - SIGNOMIX_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - SIGNOMIX_QUESTDB_CONFIG=${SGX_QUESTDB_CONFIG}
      - QUEUE_HOST=signomix-mq
      - QUEUE_PORT=5672
      - QUEUE_USER=user
      - QUEUE_PASSWORD=user
      - QUEUE_MAILING=mailing
      - QUEUE_ADMIN_EMAIL=admin_email
      - SIGNOMIX_DOC_WELCOME=/admin/welcomedoc
      - SIGNOMIX_SMSPLANET_KEY=${SGX_SMSPLANET_KEY}
      - SIGNOMIX_SMSPLANET_PASSWORD=${SGX_SMSPLANET_PASSWORD}
      - SIGNOMIX_LOG_LEVEL=${SGX_LOG_LEVEL}
    env_file:
      - path: ~/.secrets/smtp_properties.env

  signomix-auth:
    image: ${SGX_DOCKER_GROUP}${SGX_AUTH_NAME}:${SGX_AUTH_VERSION}
    container_name: signomix-auth
    hostname: signomix-auth
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    environment:
      - SIGNOMIX_ORGANIZATION_DEFAULT=${SGX_ORGANIZATION_DEFAULT}
      - SIGNOMIX_DATABASE_TYPE=${SGX_DATABASE_TYPE}
      - SIGNOMIX_DATABASE_URL=${POSTGRES_URL}
      - SIGNOMIX_AUTH_DATABASE_URL=${POSTGRES_URL}
      - SIGNOMIX_USER_DATABASE_URL=${POSTGRES_URL}
      - SIGNOMIX_DATABASE_USER=${POSTGRES_USER}
      - SIGNOMIX_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      #- QUARKUS_OTEL_TRACES_EXPORTER=${QUARKUS_OTEL_TRACES_EXPORTER}
      - SIGNOMIX_QUESTDB_CONFIG=${SGX_QUESTDB_CONFIG}
      - SIGNOMIX_LOG_LEVEL=${SGX_LOG_LEVEL}
      - GELF_ENABLED=${SGX_GELF_ENABLED}
    env_file:
      - ${SGX_SECRET_VARIABLES_FILE}

  signomix-ta-provider:
    image: ${SGX_DOCKER_GROUP}${SGX_PROVIDER_NAME}:${SGX_PROVIDER_VERSION}
    container_name: signomix-ta-provider
    hostname: signomix-ta-provider
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - signomix-ta-ms
    environment:
      - SIGNOMIX_DATABASE_URL=${POSTGRES_URL}
      - SIGNOMIX_DATABASE_USER=${POSTGRES_USER}
      - SIGNOMIX_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - SIGNOMIX_QUERY_LIMIT=${SGX_QUERY_LIMIT}
      - SIGNOMIX_QUESTDB_CONFIG=${SGX_QUESTDB_CONFIG}
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - QUARKUS_DATASOURCE_JDBC_MAX_SIZE=100
      - SIGNOMIX_LOG_LEVEL=INFO
      - GELF_ENABLED=${SGX_GELF_ENABLED}
    env_file:
      - ${SGX_SECRET_VARIABLES_FILE}

  signomix-ta-receiver:
    image: ${SGX_DOCKER_GROUP}${SGX_RECEIVER_NAME}:${SGX_RECEIVER_VERSION}
    container_name: signomix-ta-receiver
    hostname: signomix-ta-receiver
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - signomix-ta-ms
    environment:
      - SIGNOMIX_DATABASE_TYPE=${SGX_DATABASE_TYPE}
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - SIGNOMIX_EUI_HEADER_REQUIRED=${SGX_EUI_HEADER_REQUIRED}
      - SIGNOMIX_AUTHORIZATION_HEADER_REQUIRED=${SGX_AUTHORIZATION_HEADER_REQUIRED}
      - SIGNOMIX_STATUS_INTEGRATED=${SGX_STATUS_INTEGRATED}
      - QUARKUS_DATASOURCE_JDBC_MAX_SIZE=100
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
      - SIGNOMIX_LOG_LEVEL=${SGX_LOG_LEVEL}
      - GELF_ENABLED=${SGX_GELF_ENABLED}
      - SIGNOMIX_SIGNALS_USED=true
      - SIGNOMIX_DEVICES_PROTECTED=${SGX_DEVICES_PROTECTED}
    env_file:
      - ${SGX_SECRET_VARIABLES_FILE}

  signomix-ta-account:
    image: ${SGX_DOCKER_GROUP}${SGX_ACCOUNT_NAME}:${SGX_ACCOUNT_VERSION}
    container_name: signomix-ta-account
    hostname: signomix-ta-account
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    environment:
      - SIGNOMIX_DATABASE_TYPE=${SGX_DATABASE_TYPE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
      - SIGNOMIX_QUESTDB_CONFIG=${SGX_QUESTDB_CONFIG}
      - SIGNOMIX_QUESTDB_CONFIG=${SGX_QUESTDB_CONFIG}
      - SIGNOMIX_LOG_LEVEL=${SGX_LOG_LEVEL}
      - GELF_ENABLED=${SGX_GELF_ENABLED}
    env_file:
      - ${SGX_SECRET_VARIABLES_FILE}

  signomix-ta-core:
    image: ${SGX_DOCKER_GROUP}${SGX_CORE_NAME}:${SGX_CORE_VERSION}
    container_name: signomix-ta-core
    hostname: signomix-ta-core
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    environment:
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - MQ_EVENTS_QUEUE=events.core
      - SIGNOMIX_AUTH_DATABASE_URL=${SGX_AUTH_DATABASE_URL}
      - SIGNOMIX_USER_DATABASE_URL=${SGX_USER_DATABASE_URL}
      - SIGNOMIX_CMS_DATABASE_URL=${SGX_CMS_DATABASE_URL}
      - SIGNOMIX_IOT_DATABASE_URL=${SGX_IOT_DATABASE_URL}
      - SIGNOMIX_SHORTENER_DATABASE_URL=${SGX_SHORTENER_DATABASE_URL}
      - SIGNOMIX_DATABASE_TYPE=${SGX_DATABASE_TYPE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
      - QDB_USER=${QDB_USER}
      - QDB_PASSWORD=${QDB_PASSWORD}
      - QDB_URL=${QDB_URL}
      - SIGNOMIX_QUESTDB_CONFIG=${SGX_QUESTDB_CONFIG}
      - SIGNOMIX_DATABASE_MIGRATION=${SGX_DATABASE_MIGRATION}
      - SIGNOMIX_LOG_LEVEL=${SGX_LOG_LEVEL}
      - GELF_ENABLED=${SGX_GELF_ENABLED}
      - SIGNOMIX_RELEASE_VERSION=${SGX_RELEASE_VERSION}
      - SIGNOMIX_WEBAPP_VERSION=${SGX_WEBAPP_VERSION}
    env_file:
      - ${SGX_SECRET_VARIABLES_FILE}

  signomix-ta-jobs:
    image: ${SGX_DOCKER_GROUP}${SGX_JOBS_NAME}:${SGX_JOBS_VERSION}
    container_name: signomix-ta-jobs
    hostname: signomix-ta-jobs
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
    #  - signomix-mq
      - signomix-ta-ms
    environment:
      - MQ_HOST=signomix-mq
      - MQ_PORT=5672
      - MQ_USER=user
      - MQ_PASSWORD=user
      - MQ_EVENTS_EXCHANGE=events
      - SIGNOMIX_DISK_FREE_MB=${SGX_DISK_FREE_MB}
      - SIGNOMIX_LOG_LEVEL=${SGX_LOG_LEVEL}
      - GELF_ENABLED=${SGX_GELF_ENABLED}
    env_file:
      - ${SGX_SECRET_VARIABLES_FILE}

  hcms:
    image: ${SGX_DOCKER_GROUP}${SGX_HCMS_NAME}:${SGX_HCMS_VERSION}
    #image: gskorupa/cricket-hcms:1.1.0
    container_name: hcms
    hostname: hcms
    expose:
      - "8080"
    networks:
      - signomix-network
    environment:
      - FILE_TO_WATCH=version.txt;version.txt;version.txt
      - FOLDERS_EXCLUDED=.git,attic;.git,attic;.git,attic
      - HCMS_SERVICE_URL=http://documentation.localhost;http://documentation.localhost;http://documentation.localhost
      - HCMS_FILE_API=/api/file;/api/file;/api/file
      - FOLDERS_ASSETS=assets;assets;assets
      - FOLDERS_SITES=signomix-documentation;templates;news
      - FOLDERS_INDEXES=index.md;index.md;index.md
      - HCMS_REPOSITORY_LANGUAGE_MAIN=pl
      - HCMS_REPOSITORY_LANGUAGES=pl,en
      - HCMS_TRANSLATOR_TYPE=deepl
      - DEEPL_API_KEY_FILE=/run/secrets/deepl_api_key
      #- DATABASE_TYPE=h2
    volumes:
      - ${SGX_VOLUMES}/doc-templates:/home/jboss/documents/templates
      - ${SGX_VOLUMES}/documentation:/home/jboss/documents/signomix-documentation
      - ${SGX_VOLUMES}/news:/home/jboss/documents/news
    secrets:
       - deepl_api_key

  website-hcms:
    image: ${SGX_DOCKER_GROUP}${SGX_HCMS_NAME}:${SGX_HCMS_VERSION}
    container_name: website-hcms
    hostname: website-hcms
    expose:
      - "8080"
    networks:
      - signomix-network
    environment:
      - FILE_TO_WATCH=version.txt
      - FOLDERS_EXCLUDED=.git
      - HCMS_SERVICE_URL=http://www.localhost
      - HCMS_FILE_API=/api/_file
      - FOLDERS_ASSETS=assets
      - FOLDERS_SITES=signomix-website-content
      - FOLDERS_INDEXES=index.html
      - HCMS_REPOSITORY_LANGUAGE_MAIN=pl
      - HCMS_REPOSITORY_LANGUAGES=pl,en
      - HCMS_TRANSLATOR_TYPE=deepl
      - DEEPL_API_KEY_FILE=/run/secrets/deepl_api_key
    volumes:
      - ${SGX_VOLUMES}/signomix-website-content:/home/jboss/documents/signomix-website-content
    secrets:
       - deepl_api_key
  
  signomix-docs-website:
    image: ${SGX_DOCKER_GROUP}${SGX_DOCS_NAME}:${SGX_DOCS_VERSION}
    container_name: signomix-docs-website
    hostname: signomix-docs-website
    depends_on:
      - hcms
    expose:
      - "3000"
    networks:
      - signomix-network
    environment:
      PUBLIC_HCMS_URL: http://hcms:8080
      PUBLIC_HCMS_INDEX: index.md
      PUBLIC_HCMS_ROOT: signomix-documentation
      PUBLIC_HCMS_LANGUAGE: pl
      PUBLIC_HCMS_LANGUAGES: pl,en

  signomix-website:
    image: ${SGX_DOCKER_GROUP}${SGX_WEBSITE_NAME}:${SGX_WEBSITE_VERSION}
    container_name: signomix-website
    hostname: signomix-website
    depends_on:
      - website-hcms
    expose:
      - "3000"
    networks:
      - signomix-network
    environment:
      PUBLIC_HCMS_URL: http://website-hcms:8080
      PUBLIC_HCMS_INDEX: index.html
      PUBLIC_HCMS_ROOT: signomix-website-content
      PUBLIC_HCMS_LANGUAGE: pl
      PUBLIC_HCMS_LANGUAGES: pl,en

  signomix-view:
    image: ${SGX_DOCKER_GROUP}${SGX_VIEW_NAME}:${SGX_VIEW_VERSION}
    container_name: signomix-view
    hostname: signomix-view
    expose:
      - "3000"
    networks:
      - signomix-network

  signomix-webapp:
    image: ${SGX_DOCKER_GROUP}${SGX_WEBAPP_NAME}:${SGX_WEBAPP_VERSION}
    container_name: signomix-webapp
    hostname: signomix-webapp
    environment:
      - PUBLIC_WEBAPP_MODE=full
    #ports:
    #  - "3000:3000"
    expose:
      - "3000"
    networks:
      - signomix-network

  signomix-sentinel:
    image: ${SGX_DOCKER_GROUP}${SGX_SENTINEL_NAME}:${SGX_SENTINEL_VERSION}
    container_name: signomix-sentinel
    hostname: signomix-sentinel
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - signomix-network
    depends_on:
      - tsserver
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SIGNOMIX_QUESTDB_CONFIG=${SGX_QUESTDB_CONFIG}
      #- QUARKUS_OTEL_TRACES_EXPORTER=${QUARKUS_OTEL_TRACES_EXPORTER}
      - SIGNOMIX_LOG_LEVEL=${SGX_LOG_LEVEL}
      - GELF_ENABLED=${SGX_GELF_ENABLED}
      - SIGNOMIX_SIGNALS_USED=true
    env_file:
      - ${SGX_SECRET_VARIABLES_FILE}

  signomix-reports:
    image: ${SGX_DOCKER_GROUP}${SGX_REPORTS_NAME}:${SGX_REPORTS_VERSION}
    container_name: signomix-reports
    hostname: signomix-reports
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - QDB_USER=${QDB_USER}
      - QDB_PASSWORD=${QDB_PASSWORD}
      - QDB_URL=${QDB_URL}
      - SIGNOMIX_QUESTDB_CONFIG=${SGX_QUESTDB_CONFIG}
      - SIGNOMIX_QUERY_LIMIT=${SGX_QUERY_LIMIT}
      - SIGNOMIX_LOG_LEVEL=${SGX_LOG_LEVEL}
      - GELF_ENABLED=${SGX_GELF_ENABLED}
    env_file:
      - ${SGX_SECRET_VARIABLES_FILE}
    networks:
      - signomix-network
    depends_on:
      - tsserver

  signomix-broker:
    image: eclipse-mosquitto:latest
    container_name: signomix-broker
    hostname: signomix-broker
    restart: always
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ${SGX_VOLUMES}/mosquitto/config:/mosquitto/config
      - ${SGX_VOLUMES}/mosquitto/data:/mosquitto/data
      - ${SGX_VOLUMES}/mosquitto/log:/mosquitto/log
    networks:
      - signomix-network
    

  # TimescaleDB database
  # https://github.com/timescale/timescaledb-dockertimeseries
  # https://hub.docker.com/_/postgres
  tsserver:
    image: timescale/timescaledb:latest-pg15
    restart: always
    container_name: tsserver
    hostname: tsserver
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT_PUBLISHED}:5432
    expose:
      - 5432
    networks:
      - signomix-network
    volumes:
      - ${SGX_VOLUMES}/volume-postgres:/var/lib/postgresql/data:rw

  quest:
    image: questdb/questdb:8.0.1
    container_name: quest
    hostname: quest
    ports:
      - 9000:9000
#      - 9009:9009
      - 8812:8812
#      - 9003:9003
    volumes:
      - ${SGX_VOLUMES}/volume-questdb:/var/lib/questdb
    networks:
      - signomix-network

networks:
  signomix-network:
    driver: bridge

secrets:
  deepl_api_key:
    file: ~/.secrets/deepl_api_key.txt

